trigger: none 

jobs:
- job: build_image
  pool:
    vmImage: ubuntu-latest

  steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'ECRRegistry'
      repository: 'c8h4t7y5/vulnerablecontainer'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |   
       $(Build.BuildId)