
trigger: none 

jobs:
- job: build_image
  pool:
    vmImage: ubuntu-latest

  steps:
  - task: Docker@2
    inputs:
      containerRegistry: $(WoodgroveRegistry)
      repository: 'vulnerableContainer'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |   
       $(Build.BuildId)