apiVersion: v1
kind: Namespace
metadata:
  name: mdc-dcspm-demo
---
apiVersion: v1
kind: Pod
metadata:
  name: genaidemo1
  namespace: mdc-dcspm-demo
  labels:
    app: demo-1
spec:
  containers:
  - name: genaicontainer1
    image: IMAGE_NAME_PLACEHOLDER
    ports:
    - name: http
      containerPort: 80
  imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/os: linux