apiVersion: v1
kind: Pod
metadata:
  name: vulnerablecontainer1
  namespace: mdc-dcspm-demo
  labels:
    app: demo-1
spec:
  containers:
  - name: vulnerablecontainer1
    image: IMAGE_NAME_PLACEHOLDER
    ports:
    - name: http
      containerPort: 80
  imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/os: linux