apiVersion: v1
kind: Pod
metadata:
  name: vulnerablecontainer10
  namespace: alpine-dcspm-demo
  labels:
    app: demo-1
spec:
  containers:
  - name: vulnerablecontainer10
    image: alpinecontainerreg.azurecr.io/IMAGE_NAME_PLACEHOLDER
    ports:
    - name: http
      containerPort: 80
  imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/os: linux