apiVersion: v1
kind: Pod
metadata:
  name: runningvulnerablecontainer1
  namespace: alpine-dcspm-demo
  labels:
    app: demo-1
spec:
  containers:
  - name: runningvulnerablecontainer1
    image: IMAGE_NAME_PLACEHOLDER
    ports:
    - name: http
      containerPort: 80
  imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/os: linux